### ISSUE TITLE
eval command alias "ev" won't work

### ISSUE THREAD

**Issue by Error-Cookie** [3chospirits/discord-bot-template#4]
In your ./commands/dev/eval.js command you replace '${prefix}eval' with "": `var code = message.content.replace(${prefix}eval, "")`. However your command has the alias "ev". If you would try to execute the alias it wouldn't work because '${prefix}ev' wouldn't be replaced by the code mentioned earlier. My fix idea would be testing if '${prefix}eval' exists and replace it with "" else replace '${prefix}ev' with "" but this is up to you ;)

Edit:
This is my workaround for this issue:
```js
-  var code = message.content.replace(`${prefix}eval`, "").trim();

+  var code = "";
+  if (message.content.startsWith(`${prefix}eval`)) code = message.content.replace(`${prefix}eval`, "").trim();
+  else code = message.content.replace(`${prefix}ev`, "").trim();
```

**Comment by 3chospirits** [comment]
Resolved with a regex. Thanks for pointing it out!
